name: tfehelper
services:
  frontend:
    image: tfehelper.frontend
    container_name: tfehelper.frontend
    build:
      context: src/Frontend
      args:
        - REACT_APP_API_URL=http://backend:5000/api
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - frontend-network
      - backend-network

  backend:
    image: tfehelper.backend
    container_name: tfehelper.backend
    build:
      context: src/Backend
    ports:
      - "5000:5000"
    volumes:
      - tfehelper.backend.data:/app/data
    networks:
      - backend-network

volumes:
  tfehelper.backend.data:
    name: "tfehelper.backend.data"

networks:
  frontend-network:
    name: "tfehelper.frontend-network"
  backend-network:
    name: "tfehelper.backend-network"
